CREATE TABLE IF NOT EXISTS admin (
	id INTEGER PRIMARY KEY,
	name VARCHAR,
	email VARCHAR NOT NULL,
	username VARCHAR UNIQUE NOT NULL,
	pass VARCHAR NOT NULL,
    phone INTEGER,
	not_mail VARCHAR,
	not_pass VARCHAR
)
