CREATE TABLE IF NOT EXISTS {}(
	reg INT UNIQUE NOT NULL,
	name VARCHAR NOT NULL,
	course VARCHAR NOT NULL,
	stream VARCHAR NOT NULL,
	batch VARCHAR NOT NULL,
	fee INT NOT NULL,
	email VARCHAR NOT NULL
)